POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Nakke Nakuttaja",
  "dateOfBirth": "nice",
  "ssn": "010101A0101",
  "gender": "male",
  "occupation": "Cartoon Filmstar"
}